### ISSUE TITLE
key bindings

### ISSUE THREAD

**Issue by tberger2** [torque/mpv-progressbar#1]
Is it possible to define key bindings for the script?
Thank you very much!

--- Edit ---
what I mean is:
show the progress bar for a definite time by pressing a key

**Comment by torque** [comment]
It's not currently possible to do this, but implementing it shouldn't be too hard. I'll take a look in a couple of weeks when I have some free time.

**Comment by tberger2** [comment]
Enjoy it! :-)

**Comment by tberger2** [comment]
Would be great, thank you!

**Comment by torque** [comment]
I implemented this in 8ea750d0cff98ee136d7918f3c0c4fcc6c3ce230. By default, it's bound to the `tab` key and it stays on the screen for one second.

The readme has info on [how to remap the keybindings](https://github.com/torque/mpv-progressbar#keybindings). Additionally, the option `request-display-duration` controls how long the OSD is shown after the key has been released.

**Comment by tberger2** [comment]
.Exactly what I was looking for. Thank you very much!
