### ISSUE TITLE
Disable clicking the bar for a split second after toggling fullscreen

### ISSUE THREAD

**Issue by onodera-punpun** [torque/mpv-progressbar#10]
I'll explain my the problem I've encountered quite a few times now. I have a video playing in fullscreen, and toggle to windowed mode by double clicking the fullscreen window. Sometimes the second click gets registered by the progressbar which is quite annoying. I made some small screenshot illustration explaining the problems aw well:

Say I double click to toggle windowed mode at the red spot: https://sr.ht/EcIF.png
and the the windowed window is positioned like like this: https://sr.ht/xRXh.png, it will actual register the second click and jump to that spot in the timeline.

**Comment by torque** [comment]
Thanks for the detailed explanation. I can't reproduce this on OS X, so I'm not sure if this is X11/your WM's fault or mpv's fault, but it seems odd to me that the second click of a double click action would leak through as an independent single click event.

I can try to mitigate this on `progresbar.lua`'s end by looking for fullscreen transitions, but I wonder if that would actually fire fast enough to fix the problem. I also expect this would happen with the built-in osc. I'll ask around and find out if this is a known issue.

**Comment by grimnight** [comment]
Open a video file to play.
Let it play a little while or fast forward.
Press `f`. Do not move the mouse.
If you move the mouse at this point the progress bar disappears and the following does not happen.
See the three number counts above the progress bar, the middle one, current posiition shows `00:00:00`.
Now press `MOUSE_BTN0` or whatever you have set as `script-binding progressbar/seek-to-mouse`.
Watch as the video file starts again from the beginning.

Using `MOUSE_BTN0_DBL` causes the same thing to happen, but it can be too fast to realise what happened.

I am on OS X using mpv 0.17.0.

**Comment by torque** [comment]
What you've described is a subtly different issue and is mpv's fault, though I still don't see how a single click event would get issued _after_ a double click event unless the mouse was clicked a minimum of three times.

Ultimately, that doesn't matter, though. I'll try to add a workaround that will hopefully address both of these problems.

**Comment by grimnight** [comment]
I still experience the behavior with double click, but only with double click.
I have assigned `MOUSE_BTN2 cycle fullscreen` and `MOUSE_BTN0_DBL ignore`, now everything works fine.

**Comment by torque** [comment]
I suspect that this could be fixed by further tweaking the click-to-seek delay I introduced in the workaround. But since I couldn't reproduce this 100% of the time even before the workaround and I don't know how accurate the timer is in mpv anyway, I'm not convinced there's much more I can do on this end.
