### ISSUE TITLE
Don't seek to keyframes

### ISSUE THREAD

**Issue by FichteFoll** [torque/mpv-progressbar#12]
Imo it makes more sense not to seek to keyframes when clicking on the progress bar. I generally prefer software doing what I want it to instead of trying to be a smartass and waging little performance gains against precision.

Furthermore, when clicking on a position in the progressbar, mpv will usually go to the next keyframe following the position clicked *in the direction it is seeking*. Thus, clicking the same position more than once will toggle between adjacent keyframes consistently, which is rather irritating.

I changed this locally, but you might want to apply it upstream too.

FYI, according to the manual the third parameter to `seek` has been deprecated and `absolute-relative+exact` as the second parameter should be used instead.

**Comment by torque** [comment]
Yeah, I'd been thinking about this recently, and I agree with you. Thanks for the notes on the changed command syntax as well.
