### ISSUE TITLE
Customizable margins for top title and current/remaining time

### ISSUE THREAD

**Issue by FichteFoll** [torque/mpv-progressbar#13]
Currently, the top title and the current and remaining time displays are *really* close to the window boundaries. I would like if there were small margins between them and the window edges. Since this is font-dependant, it has to be configurable.

**Comment by torque** [comment]
This is obviously doable but I'll need to put some thought into it. For example, changing the margins should probably change the mouse hitboxes, at least vertically.

**Comment by FichteFoll** [comment]
Thank you for the changes.

Could you make a new build as well?

**Comment by torque** [comment]
Done.
