### ISSUE TITLE
Better handling for continuous streams with unknown duration

### ISSUE THREAD

**Issue by FichteFoll** [torque/mpv-progressbar#14]
A progressbar in general is useless for continuous streams that do not have a known duration. However, the title display (and elapsed time) still are useful.

**Comment by torque** [comment]
Now that I actually have some free time I should be able to implement this. I just need to check how mpv reports unknown length streams.

**Comment by FichteFoll** [comment]
Thanks!

>Hopefully there is not some weird edge case where stream duration suddenly becomes known in the middle of playback because that is not handled at all.

A likely use case for this is switching the video from a stream to an actual video, e.g. by dragging a video file onto the player. I verified that the progressbar remains in stream mode.

Perhaps subscribe to a media changed event?

**Comment by torque** [comment]
The problem isn't that I'm missing an event, the problem is I'm an idiot. Will fix soon.
