### ISSUE TITLE
Option or hotkey to disable inactive progress bar in fullscreen

### ISSUE THREAD

**Issue by FichteFoll** [torque/mpv-progressbar#15]
When watching something in fullscreen, the progress bar is mildly irritating. I'd love to have an option to disable it when it's "inactive".

Maybe also add a hotkey to toggle in general? I don't know anything about mpv scripting but I think it's possible.

**Comment by onodera-punpun** [comment]
>Maybe also add a hotkey to toggle in general? I don't know anything about mpv scripting but I think it's possible.

something like this would be really nice yeah

**Comment by torque** [comment]
Sounds like there are a few different potential desired behaviors here.

To "disable" the bar when it's inactive, you can set `bar-height-inactive=0` in the config. If you only want it disabled in fullscreen, that's not currently possible (and I'm not terribly inclined to implement separate windowed/fullscreen behavior).

A key to toggle it in general is definitely possible, at least for toggling the entire script on or off. I assume you're not looking for a toggle between inactive and active states.

**Comment by FichteFoll** [comment]
I was rather looking for a toggle to set the inactive state height to 0 or "config value". If a separate behavior is not desired, I would be perfectly fine with the hotkey toggle instead.

**Comment by torque** [comment]
Oh, so you want a hotkey to toggle whether or not the inactive progress bar is visible? that's certainly doable too, I just didn't understand that's what you wanted initially.

**Comment by onodera-punpun** [comment]
By adding that OP could also archive the hiding of the bar when entering fullscreen by binding both "toggle fullscreen" and "toggle progressbar" to the F key, not usre if you can do the same for double click.

**Comment by FichteFoll** [comment]
Double click is a binding too, so that would work nicely indeed.

**Comment by torque** [comment]
The binding `script-binding progressbar/toggle-inactive-bar` will toggle whether or not the bar displays when inactive. Hopefully this works as expected.

**Comment by FichteFoll** [comment]
Awesome, works like a charm!

The default binding is <kbd>c</kbd>, for anyone interested.
