### ISSUE TITLE
[osd/libass] Failed to process glyph outline! "errors"

### ISSUE THREAD

**Issue by bendooru** [torque/mpv-progressbar#20]
I'm using Arch Linux, latest mpv release and latest progressbar.
This started happening after upgrading to libass-0.13.3-1, so it might be a libass bug.
Playing a video prints a single

```
[osd/libass] Failed to process glyph outline!
[osd/libass]
```

and if the progressbar is hidden via `bar-height-inactive=0`, the error message is repeated several times per second as well.
Increasing output verbosity does not really provide any more info.
This (seemingly) does not actually affect the progressbar or text, so it can be "fixed" by muting the terminal output, but I wanted to point it out just in case.

**Comment by torque** [comment]
Looks like 0.13.3 included some changes to the libass stroking code, so I'll upgrade and see if I can reproduce and track down what exactly is causing this.

**Comment by FichteFoll** [comment]
I've had this for quite some time too until I updated mpv which made it go away. I'm on WIndows though.

**Comment by torque** [comment]
I just rebuilt libass and mpv and I can reproduce this. I suspect the stroker code doesn't like the 0-height progress bar (even though it's not even stroked to begin with). Will spend some time trying to track down whether or not I think this is libass's fault and probably implement a hacky workaround.

**Comment by torque** [comment]
I've finally gotten around to tracking this down to libass/libass@6a61a7a96bd3ba1e7858c06f44d619f814af6b42. This isn't technically a problem with libass itself, but the resulting message spew is annoying. I'll complain about this, but I expect the reply to be that zero-size shapes are dumb and shouldn't exist (which is fair), so I'll also add a workaround.
