### ISSUE TITLE
Inactive marker height

### ISSUE THREAD

**Issue by sCreami** [torque/mpv-progressbar#27]
What's that useless grey space above the inactive progressbar ?
I don't like it, Scot.

![screen shot 2016-12-31 at 20 49 41](https://cloud.githubusercontent.com/assets/1769603/21579058/3856a3a2-cf9b-11e6-88d0-5b1a9f4f13af.jpg)

**Comment by sCreami** [comment]
Conf file btw
http://sprunge.us/EAMW

**Comment by torque** [comment]
Looks like it's the border. You should set `bar-default-style=\bord0` in your config.

**Comment by sCreami** [comment]
Perfect!
