### ISSUE TITLE
Chapter markers ignore settings

### ISSUE THREAD

**Issue by bendooru** [torque/mpv-progressbar#3]
Chapter markers ignore `bar-height-{in,}active` settings.

**Comment by torque** [comment]
The chapter markers are really poorly tested since I hardly ever watch anything with chapters, and I'm sure they have more problems than just this. I'll take a look generally improving them.

**Comment by torque** [comment]
I've fixed this and [improved configurability](https://github.com/torque/mpv-progressbar/blob/master/torque-progressbar.conf#L50-L55), although the chapter markers haven't quite reached full parity with their old behavior yet.
