### ISSUE TITLE
Is it possible to change UI color depending on which source is playing?

### ISSUE THREAD

**Issue by shizeeg** [torque/mpv-progressbar#30]
Here is my idea:

By default torque-progressbar uses twitch color scheme, but there are many other streaming services with their own color schemes. For ex. https://stream.me/ uses shade of orange, https://youtu.be/ uses red, so it would be nice to detect currently playing source and change color scheme accordingly.

I see it implemented like some sort of profiles, for example:

```ini
[youtube]
url-regex="(https?)://(?:www.)?youtube.com.*"
bar-default-style=\c&Hc4302b&

[twitch]
url-regex="(https?)://(?:www.)?twitch.tv.*"
bar-default-style=\bord0
```

**Comment by torque** [comment]
This is a pretty cool idea, actually, though the current default isn't intended to match twitch, it's just a shade of purple I like. Ironically, if you're watching actual streams and not VODs, the progress bar shouldn't even appear.

That said, the implementation needs some thought, and I'm pretty busy with life at the moment, so it may be a long time before I get around to it.

**Comment by shizeeg** [comment]
life is life.. It is good time to me to start learning a new scripting language then. :)

I'm not a huge fan of a former and current `mpv` OSCs, so `torque-progressbar.lua` is a wonderful replacement. Thanks for your project!

**Comment by Argon-** [comment]
It's probably easier to use mpv's autoprofiles [1] and "just" modify this script to support getting values from `--script-opts`?
This way you could create profiles in mpv.conf like:


    [progressbar-youtube]
    profile-desc=cond:get("filename") == ...
    script-opts=bar-default-style=\c&Hc4302b&
    
    [progressbar-twitch]
    profile-desc=cond:get("filename") == ...
    script-opts=bar-default-style=\bord0

[1] https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua

**Comment by torque** [comment]
This is a clever solution. I wasn't aware of the auto-profiles script. I am already using mpv's built-in option parsing, so e.g. `script-opts=torque-progressbar-bar-foreground-style=\c&HFFFFFF&` Just Works.

**Comment by Argon-** [comment]
Are you sure? It doesn't work for me, e.g. using

    script-opts=torque-progressbar-bar-foreground-style=\c&HFFFFFF&

Has no effect. IIRC mpv's `read_options` does not retrieve values specified by this, you have to explicitly use `mp.get_opt(key)`. At least I had to when I used this once.

**Comment by torque** [comment]
I tried it from the command line last night, but I have tested it now with the setting in `mpv.conf`, and it appears to work fine.

**Comment by Argon-** [comment]
Oh I'm sorry you are right... When I tested it in `mpv.conf` it was part of a not-yet closed `[profile]`...
