### ISSUE TITLE
FR: show just a dot (instead of a line) on progress bar

### ISSUE THREAD

**Issue by Drugoy** [torque/mpv-progressbar#38]
I have configured progress bar to be always displayed.
To make it less intrusive I've set its height to just 1px.
Bit since I use green color for the progress bar - it still is pretty much intrusive.
I'd prefer if there was just a don (or a few dots) instead of a line to signalize the progress.

Please, add this feature.

**Comment by torque** [comment]
I'll update the build some time tomorrow.

**Comment by torque** [comment]
I updated the built script. You can use the new `progress-bar-width` setting to control the maximum width of the bar.

**Comment by Drugoy** [comment]
Thanks for the update, just tried it.
Is there a way to make the rest of the bar transparent? Currently it's a grey line, which is less intrusive than green, but still pretty much noticeable.

**Comment by torque** [comment]
To hide the bar background you can set the options as follows

```ini
bar-cache-style=\alpha&HFF&
bar-background-style=\alpha&HFF&
```
