### ISSUE TITLE
How to change the colour?

### ISSUE THREAD

**Issue by intre4si32** [torque/mpv-progressbar#39]
Hello,
I use it on Windows. It works and I would use a different colour to have more contrast but do not understand which piece of code should I change. Could you please help me? Thanks

**Comment by torque** [comment]
You can change colors using a configuration file. The windows builds should either have the config in the same folder as mpv.exe (in a folder named `mpv`) or in `%appdata%\mpv`. You can see more about these file locations in the mpv docs [here](https://mpv.io/manual/master/#files-on-windows).

In the mpv config directory, you need to create a new directory named `lua-settings` and in that new directory create a file named `torque-progressbar.conf`. In this config file, you can change the foreground color to e.g. bright green by adding the line

<code>
default-style=\fnSource Sans Pro\b1\bord2\shad0\fs30<b>\c&H00FF00&</b>\3c&H2D2D2D&
</code>

I've bolded the component of this that was changed from the [default config](https://github.com/torque/mpv-progressbar/blob/master/torque-progressbar.conf#L16-L38), which sets the foreground color of the interface.
