### ISSUE TITLE
Pause indicator standalone script

### ISSUE THREAD

**Issue by Keith94** [torque/mpv-progressbar#47]
Is there a way to get a version of this script which only includes the pause indicator features? I am mostly interested in just that feature and disabling other progress bar features manually takes me a while.

**Comment by torque** [comment]
I can certainly build you a version that only includes that functionality. In general, while I've attempted to design the different UI components to be somewhat modular, they're simply too entangled with the custom draw loop to easily extract them.

That said, [here's a compiled copy of the script][compiled] that strips out all of the non-pause-indicator functionality. I've pushed the corresponding source to the [pause-indicator-only][branch] branch, if you care about that.

[compiled]: https://gist.github.com/torque/9dbc69543118347d2e5f43239a7e609a
[branch]: https://github.com/torque/mpv-progressbar/tree/pause-indicator-only

**Comment by Keith94** [comment]
Thank you for that! I will provide feedback once I get a chance to test it.
