### ISSUE TITLE
Improve color configuration by introducing a base color setting

### ISSUE THREAD

**Issue by 8ware** [torque/mpv-progressbar#5]
Instead of adjusting the color for each single item it would be convenient to configure a base color which is used for all of them by default. Any color configuration of an individual item would override the base color setting which will maintain backward compatibility and keep the fine grained configuration capabilities.

A solution could be to assign a placeholder instead of the default value to the individual color settings. After reading the options through MPV all color settings which are still assigned to the placeholder could be replaced by the value given as base foreground and background color, respectively. Any color value which is explicitly assigned to an individual item would keep its value, though.

**Comment by torque** [comment]
This has been resolved in the PR referenced above.
