### ISSUE TITLE
Does not escape % character in titles

### ISSUE THREAD

**Issue by FichteFoll** [torque/mpv-progressbar#54]
When opening a video whose title contains `%s`, progressbar.lua errors and stops working. It doesn't even come back when I change to a different video.

Example video: https://twitter.com/_jp53/status/1114233699652923392?s=21
Text: `Zelda can space short hop drifting dair in neutral as a fairly safe option, she can’t get as many conversions as fast fall dair but can still kill confirm with a rising dair at mid %s
#SSBU_Zelda`

Exception:
```
progressbar: stack traceback:
progressbar: 	[C]: in function 'format'
progressbar: 	/home/fichte/.config/mpv/scripts/progressbar.lua:10: in function </home/fichte/.config/mpv/scripts/progressbar.lua:9>
progressbar: 	(...tail calls...)
progressbar: 	/home/fichte/.config/mpv/scripts/progressbar.lua:2470: in function 'handler'
progressbar: 	mp.defaults:486: in function 'call_event_handlers'
progressbar: 	mp.defaults:520: in function 'dispatch_events'
progressbar: 	mp.defaults:479: in function <mp.defaults:478>
progressbar: 	[C]: in ?
progressbar: 	[C]: in ?
progressbar: Lua error: /home/fichte/.config/mpv/scripts/progressbar.lua:10: bad argument #1 to 'format' (no value)
```

Related: https://github.com/jonniek/mpv-playlistmanager/issues/26

**Comment by FichteFoll** [comment]
I should mention that I use mpv 0.31.0 on Arch Linux and mpv uses a Lua version of 5.2, according to a debug print in a test mpv script on `_G._VERSION`.

**Comment by torque** [comment]
Yeah, I've reproduced this several times over the last couple of years. I don't have an ssh key on this computer I can use with github, but this should be a trivial fix. I will try to get this addressed soon.
