### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by jimmy-1000** [torque/mpv-progressbar#57]
I tried to change the color of purple bar below but I could't, any help?

**Comment by brckts** [comment]
You have bar style related options in script-opts/torque-progressbar/main.conf, bar-foreground-style and bar-background-style are probably what you are looking for. Note however that these take ASS override tags, not RGB values.

If you just want to specify the colour, set them to `\c&HBBGGRR&` with BB being you blue hex value, GG your green and RR your red.

Hope that helped!

**Comment by jimmy-1000** [comment]
> 
> 
> You have bar style related options in script-opts/torque-progressbar/main.conf, bar-foreground-style and bar-background-style are probably what you are looking for. Note however that these take ASS override tags, not RGB values.
> 
> If you just want to specify the colour, set them to `\c&HBBGGRR&` with BB being you blue hex value, GG your green and RR your red.
> 
> Hope that helped!

Thanks but I couldn't. I did many changes to mpv in functionality and appearance, but change the color to this bar in this lua was impossible.

**Comment by jimmy-1000** [comment]
> You have bar style related options in script-opts/torque-progressbar/main.conf, bar-foreground-style and bar-background-style are probably what you are looking for. Note however that these take ASS override tags, not RGB values.
> 
> If you just want to specify the colour, set them to `\c&HBBGGRR&` with BB being you blue hex value, GG your green and RR your red.
> 
> Hope that helped!

Thanks !!
