### ISSUE TITLE
Hovered timestamp not updated when switching files

### ISSUE THREAD

**Issue by po5** [torque/mpv-progressbar#63]
When switching files with the mouse hovered on the timeline, duration and current time get updated without having to move the mouse, but hovered time doesn't.

**Comment by torque** [comment]
This was due to the `HoverTime` not taking into account a possibly changed file duration on redraw. Fixed in https://github.com/torque/mpv-progressbar/pull/62/commits/7459d8a08a094e05790d3fb6cf6875b827a992aa
