### ISSUE TITLE
request-display and keybindings not working over socket

### ISSUE THREAD

**Issue by rdrr** [torque/mpv-progressbar#8]
progressbar/request-display is great, however, I use a socket (via --input-ipc-server) in order to use a bunch of global keybindings and none of the progressbar keybindings seem to work when sent over the socket.  Other scripts seem to work (such as stats.lua).  And neither the keybinding (via "echo 'keypress TAB' | socket - $socket") or the actual command (via echo '{"command": ["script-binding", "progressbar/request-display"] }' | socat - $socket") seem to work.

**Comment by torque** [comment]
This was an oversight in how `request-display` was implemented. Thanks for reporting the bug.
