### ISSUE TITLE
Add shadow color, size, spread, opacity, ec.t to the settings list.

### ISSUE THREAD

**Issue by onodera-punpun** [torque/mpv-progressbar#9]

**Comment by torque** [comment]
I don't think this is particularly reasonable to implement currently.

The "correct" way to do this, in my view, would be to extend the mpv ASS OSD API to allow script-specified styles. Implementing that nicely probably requires some rumination and I don't even know if The Mpv Maintainers would be receptive to such a proposal. That said, now that each script has its own ASS renderer/library, this should be much more feasible to do in mpv.

**Comment by torque** [comment]
This is mostly possible now if you're familiar with basic ASS override tags. The recent changes introduced the settings `default-style`,  `bar-default-style`, `bar-foreground-style`, and so on (search the default config for `-style` to find all the available settings).
